name: Backend Deploy to EC2 (PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # NOTE: AWS credentials are included for completeness but not strictly needed for this specific SSH-based script.

      # --- CRITICAL: DEPLOY BACKEND VIA SSH ---
      - name: Deploy and Restart Backend via PM2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: 3.110.182.77
          username: ec2-user

          # The commands to run on the EC2 instance
          script: |
            # Directory where the code will live on the EC2 instance
            BACKEND_DIR="/home/ec2-user/eventDeploybckend"
            MAIN_FILE="server.js" # <-- **CONFIRM YOUR MAIN BACKEND FILE NAME HERE (e.g., app.js, index.js, server.js)**

            echo "1. Deploying/updating backend code..."
            if [ ! -d "$BACKEND_DIR" ]; then
              # If directory doesn't exist, clone the repo
              git clone https://github.com/Kaushalcollege/eventDeploybckend.git $BACKEND_DIR
            fi

            cd $BACKEND_DIR
            git pull origin main

            echo "2. Installing/updating dependencies..."
            npm install

            # 3. Start or reload the application using PM2
            # Use 'pm2 start' only for the first deployment, then 'pm2 reload'
            echo "3. Starting/reloading app with PM2..."
            pm2 start $MAIN_FILE --name "event-backend" || pm2 reload "event-backend"

            # 4. Save PM2 state for persistence on reboot
            pm2 save

            echo "Deployment complete."
