name: Backend Deploy to EC2 (PM2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # --- SECURE DEPLOYMENT VIA AWS SSM ---
      - name: Deploy Backend to EC2 via SSM
        run: |
          echo "--- Sending SSM Command for Backend ---"
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "echo --- 1. Navigating to backend directory ---",
              "cd /home/ec2-user/eventDeploybckend",
              
              "echo --- 2. Forcing pull of latest code ---",
              "git fetch --all",
              "git reset --hard origin/main",
              
              "echo --- 3. Installing dependencies ---",
              "npm install",
              
              "echo --- 4. Loading environment and restarting PM2 ---",
              "source /home/ec2-user/.bashrc",
              "pm2 restart event-backend",
              
              "echo --- Backend deploy complete ---"
            ]'
